setRepositories(ind=1:3)
install.packages("devtools")
library("devtools")
install_github("hadley/devtools")
install.packages("org.Hs.eg.db")
install.packages("EnsDb.Hsapiens.v75")
install.packages("GO.db")
install_github("mathelab/ALTRE",ref="webgraphs")
library("ALTRE")
# don't permamently replace the user's devtools
install.packages("devtools")
